baseURL = "/"
languageCode = "en"
title = "Leela Chess Zero"
theme = "leela"
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
enableGitInfo = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
disableDefaultLanguageRedirect = false
enableMissingTranslationPlaceholders = true
[languages]
  # [languages.de]
    # contentDir = 'content/de'
  #   disabled = true
    # languageCode = 'de-DE'
    # languageDirection = 'ltr'
    # languageName = 'Deutsch'
    # title = 'Projekt Dokumentation'
  #   weight = 2
    # [languages.de.params]
    #   subtitle = 'Referenz, Tutorials und Erklärungen'

  [languages.es]
    weight = 2
  [languages.en]
    # contentDir = 'content/en'
    # disabled = false
    # languageCode = 'en-US'
    # languageDirection = 'ltr'
    # languageName = 'English'
    # title = 'Project Documentation'
    weight = 1
    # [languages.en.params]
    #   subtitle = 'Reference, Tutorials, and Explanations'

[[menu.main]]
    name = "Play"
    url = "/play/quickstart"
    weight = 20

[[menu.main]]
    name = "Watch"
    url = "/watch"
    weight = 30

[[menu.main]]
    name = "Contribute"
    url = "/contribute"
    weight = 40

[[menu.main]]
    name = "Development"
    url = "/dev"
    weight = 50

[[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 70

[params]
  lc0version="v0.32.0"
  google_analytics_id="G-MC971PFSYE"
  math = false

  #homepage_intro = 'Lc0'
  mainSections = ["play", "watch", "contribute", "dev", "community", "blog"]
  [[params.homepage_button]]
    link = "/play/download"
    text = "Download"
  [[params.homepage_button]]
    link = "/play/quickstart"
    text = "Quick start"

  [permalinks]
    blog = "/blog/:year/:month/:slug/"

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Leela Chess Zero is an open source neural network based chess engine."
    meta_og_title = "Leela Chess Zero"
    meta_og_type = "website"
    meta_og_url = "https://lczero.org"
    # meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "Leela Chess Zero is an open source neural network based chess engine."
    meta_twitter_card = "summary"
    meta_twitter_site = "@leelachesszero"

  [params.logo]
      mobile = "/images/logo.svg"
      standard  = "/images/logo.svg"

  [[params.footerIcons]]
    url = "https://lczero.org/blog/index.xml"
    icon = "qlementine-icons--rss-24"
    name = "RSS Feed"
  
  [[params.footerIcons]]
    url = "https://github.com/LeelaChessZero/"
    icon = "qlementine-icons--github-fill-24"
    name = "GitHub"
  
  [[params.footerIcons]]
    url = "https://discord.gg/pKujYxD"
    icon = "qlementine-icons--discord-fill-24"
    name = "Discord"
  
  [[params.footerIcons]]
    url = "https://x.com/leelachesszero"
    icon = "qlementine-icons--x-24"
    name = "X (Twitter)"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]