name: Build Draft Preview

on:
  pull_request_target:
    types: [opened, synchronize, closed, reopened]

jobs:
  trigger_draft_build:
    runs-on: [self-hosted, draft-builder]

    steps:
      - name: Call Draft Management Script
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_ACTION: ${{ github.event.action }}

        run: |
          /home/lc0/scripts/lczero-build-draft.py --pr=$PR_NUMBER --action=$PR_ACTION --github_step_summary=$GITHUB_STEP_SUMMARY
